### ISSUE TITLE
The matching algorithm seems not work

### ISSUE THREAD

**Issue by alvin528** [arkhodakov/super-tribble#3]
We uploaded our results, but the IOU score was 0. We downloaded the Error log file and found this problem in the visualization.
![11_MedOffice_05-F4](https://user-images.githubusercontent.com/50798865/172641468-ba3926bc-c08c-472f-ac80-e5a27c48a724.jpg)

**Comment by alvin528** [comment]
Btw, why do we need this align function in matching.py?
`
def align(gt_normalized: np.ndarray, tg_normalized: np.ndarray) -> Tuple[float, np.ndarray, np.ndarray]:
`
If both ground truth and prediction result are from the same point cloud file, they are already aligned in coordinates (similar to 2D Task), and there is no need to calculate rotation Angle and shift distance. If we register through the point cloud composed of bouding box points, the whole coordinate may be wrong. Because the distribution of bounding boxes of ground truth and prediction is different, and we have no way to know the generation rule of bounding boxes in Ground truth (for example, whether and when the bounding boxes of two connected walls need to be cut).

**Comment by arkhodakov** [comment]
Hey @alvin528,
Could you share you .json data with me so that I can check it up?

**Comment by alvin528** [comment]
@arkhodakov  OK. I have sent it to your email address: Artem.Khodakov.workbox Did you get it?

**Comment by arkhodakov** [comment]
> @arkhodakov OK. I have sent it to your email address: Artem.Khodakov.workbox Did you get it?

Yep, I got it. Give me an hour to check your data.
I'll mention you if any question arises.

**Comment by arkhodakov** [comment]
@alvin528, I just checked your data and especially 11_MedOffice_05 model and it works just fine.
If you can reproduce it locally we can have a call so that I can glance through your logs.

**Comment by alvin528** [comment]
@arkhodakov 
Because I don't have the ground truth data, I can't reproduce it locally. So I uploaded my JSON data on the evaluation server just now. I have downloaded all the log files and sent them to you via email.

**Comment by arkhodakov** [comment]
@alvin528, as you mentioned above the point cloud registration algorithm made errors with translation and scale. It is going to be disabled by default. Right now the update is online and you can test as usual. If no errors will occurre please close the issue.
Could you only tell me, how you managed to perfectly align your data?

**Comment by alvin528** [comment]
@arkhodakov 
Thank you so much for your work.
We do not need align data because we do not translate or rotate the raw point cloud. The prediction results' coordinate system is consistent with the raw point cloud. The coordinate system of both ground truth and prediction results is consistent with the original point cloud. Naturally they are perfectly aligned.

**Comment by arkhodakov** [comment]
@alvin528
Thanks for clarifying!
Contact me if any other errors will occure.
